### ISSUE TITLE
Loading a file after calling `prepareExecution` method doesn't seem to work.

### ISSUE THREAD

**Issue by jahangirmohammed** [uzh/triplerush#21]
The problem seems to be either loading file after calling `prepareExecution` doesn't work or my usage of the API.

The issue is recreated on branch: `bug-prepare-execution` and the test which showcases this issue is below :
https://github.com/uzh/triplerush/blob/9ddef512ab2b03d34f31c744900b82f6e4e0eaaa/src/test/scala/com/signalcollect/triplerush/sparql/RecreateBug.scala

**Comment by pstutz** [comment]
This requires a several fixes:
- We need to disable the query optimizer with `val tr = new TripleRush(optimizerCreator = _ => None)`: the stats are wrong this way so the optimizer could produce garbage (decide a query has no results when it does).
- If we later on should fix the optimizer, then we we either have to call `TripleRush.resetCaches` if a query was executed before, or we need to incrementally fix the cached stats.
- We should call `TripleRush.awaitIdle` after giving the load command, because it is non-blocking.
- `loadNtriples` uses Signal/Collect `GraphEditor.loadGraph` underneath, which has the following comment `IMPORTANT: Only works while the computation is not yet executing.`. Unfortunately `TripleRush.prepareExecution` executes the Signal/Collect computation.
Everything apart from the last one is easy to address. For the last one I'd first have to research why I decided at the time that this function should only work during the loading phase.

**Comment by pstutz** [comment]
https://github.com/uzh/triplerush/issues/23 will fix this, will be in S/C 4.0.0, which I'll release as soon as I'm convinced that it enables my idea for blocking triple additions.
